#!/usr/bin/env sh
app_name=$1
app_path=/data/code/$app_name

if [ -z "$app_name" ]; then
  echo "usage: $0 <NEW_APP_NAME>"
  exit 1
fi

if [ -d "$app_path" ]; then
  rails_command="echo $app_path exists, skipping rails new"
else
  rails_command="rails new $app_path"
fi

$rails_command &&
cp .editorconfig .envrc .ruby-version devbox.json $app_path &&
sed -i "s/APP_NAME/$1/g" $app_path/devbox.json
cat .gitignore >> $app_path/.gitignore
cd $app_path
direnv allow
bundle install
git add .
git ci -am "$rails_command"
git remote add origin git@github.com:PhilT/$app_name.git
git push -u origin main
